#!/bin/bash -e

required_bin="bin/setup bin/control"
optional_bin="bin/teardown bin/runhook bin/build"

errors=0
warnings=0

function error() {
  echo -e 1>&2 "ERROR: $1"
  ((errors = errors + 1))
}

function warn() {
  echo -e 1>&2 "WARN : $1"
  ((warnings = warnings + 1))
}

function info() {
  echo -e 1>&2 "INFO : $1"
}

for f in $required_bin; do 
  [ ! -s $f ] && error "Required file $f is missing or empty."
done

for f in $required_bin $optional_bin; do 
  if [ -f $f ]; then
    [ ! -x $f ] && error "Invalid mode on $f. Must be executable."
    [ ! -s $f ] && warn "$f is empty."
  fi
done

if (( 0 == errors && 0 == warnings )); then
  exit 0
else
  echo -e 1>&2 "\nErrors reported:   $errors\nWarnings reported: $warnings"
  exit 1
fi
